services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      app:
        condition: service_started

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/metricsdb
      SPRING_DATASOURCE_USERNAME: metrics
      SPRING_DATASOURCE_PASSWORD: metrics
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      APP_JWT_SECRET: replace-this-with-a-long-secure-base64-secret-replace-this-with-a-long-secure-base64-secret
      APP_JWT_TTL_SECONDS: 3600
      APP_RATE_LIMIT_PER_CLIENT_RPS: 10
      APP_RATE_LIMIT_GLOBAL_RPS: 1000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: metricsdb
      POSTGRES_USER: metrics
      POSTGRES_PASSWORD: metrics
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U metrics -d metricsdb" ]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
